### ISSUE TITLE
Error initializing app: NameError: name 'iysraq_time' is not defined

### ISSUE THREAD

**Issue by iqfareez** [zubir2k/HomeAssistantEsolatGPS#1]
From AppDaemon's log

```
2024-05-09 17:02:57.364316 INFO AppDaemon: Calling initialize() for esolat_gps
2024-05-09 17:02:57.627692 WARNING esolat_gps: ------------------------------------------------------------
2024-05-09 17:02:57.628489 WARNING esolat_gps: Unexpected error running initialize() for esolat_gps
2024-05-09 17:02:57.629229 WARNING esolat_gps: ------------------------------------------------------------
2024-05-09 17:02:57.634890 WARNING esolat_gps: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/esolat_gps.py", line 17, in initialize
    self.update_sensors(None)
  File "/config/apps/esolat_gps.py", line 44, in update_sensors
    self.update_prayer_time("sensor.esolat_home", "esolat_home", "Home Prayer Time", home_icon, home_latitude, home_longitude, "zone.home")
  File "/config/apps/esolat_gps.py", line 88, in update_prayer_time
    isyraq_12h = self.convert_to_local_12time(iysraq_time.timestamp())
                                              ^^^^^^^^^^^
NameError: name 'iysraq_time' is not defined

2024-05-09 17:02:57.635338 WARNING esolat_gps: ------------------------------------------------------------
```

AppDaemon version:

![image](https://github.com/zubir2k/HomeAssistantEsolatGPS/assets/60868965/54818f11-07ae-48ff-8230-3a6e4de3eef4)

**Comment by zubir2k** [comment]
Noted on the typo error. Thanks for highlighting 👍 will correct it in the next release.

**Comment by zubir2k** [comment]
Salam @iqfareez 

I have prepared a custom integration as a successor to this Appdaemon. 
[https://github.com/zubir2k/homeassistant-esolatgps](https://github.com/zubir2k/homeassistant-esolatgps)
